 drop table if exists EDUCATION CASCADE
 drop table if exists EXPERIENCE CASCADE
 drop table if exists PROFILE CASCADE
 drop table if exists PROFILE_EDUCATION CASCADE
 drop table if exists PROFILE_PROJECT CASCADE
 drop table if exists PROFILE_SKILL CASCADE
 drop table if exists PROFILE_WORK_EXPERIENCE CASCADE
 drop table if exists PROJECT CASCADE
 drop table if exists SKILL CASCADE
 drop table if exists SKILL_EXPERIENCE CASCADE
 drop table if exists USER_INFO CASCADE
 drop sequence if exists hibernate_sequence
 create sequence hibernate_sequence start with 1 increment by 1
 create table EDUCATION (id bigint generated by default as identity, college varchar(255), date_from timestamp, date_to timestamp, degree varchar(255), description varchar(255), primary key (id))
 create table EXPERIENCE (id bigint generated by default as identity, company varchar(255), date_from timestamp, date_to timestamp, description varchar(255), job_title varchar(255), primary key (id))
 create table PROFILE (id bigint not null, primary key (id))
 create table PROFILE_EDUCATION (Profile_id bigint not null, educationList_id bigint not null)
 create table PROFILE_PROJECT (Profile_id bigint not null, projectList_id bigint not null)
 create table PROFILE_SKILL (Profile_id bigint not null, skillList_id bigint not null)
 create table PROFILE_WORK_EXPERIENCE (Profile_id bigint not null, workExperienceList_id bigint not null)
 create table PROJECT (id bigint generated by default as identity, date_from timestamp, date_to timestamp, description varchar(255), title varchar(255), project_type char(255), college_id bigint, company_id bigint, primary key (id))
 create table SKILL (id bigint generated by default as identity, rating integer not null, title varchar(255), years_of_experience integer, primary key (id))
 create table SKILL_EXPERIENCE (skills_id bigint not null, experiences_id bigint not null)
 create table USER_INFO (id bigint generated by default as identity, contact_number varchar(255), email_address varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), username varchar(255), profile_id bigint, primary key (id))
 alter table PROFILE_EDUCATION add constraint UK_nksmphglklemgvdwjxlwdcvaw unique (educationList_id)
 alter table PROFILE_PROJECT add constraint UK_2xqo2gldiy3tvei9pga5ctviq unique (projectList_id)
 alter table PROFILE_SKILL add constraint UK_ory14gb8h29u2byw1wbly2tc1 unique (skillList_id)
 alter table PROFILE_WORK_EXPERIENCE add constraint UK_c4ql7tw1kg796n5ixuvxdd5x1 unique (workExperienceList_id)
 alter table USER_INFO add constraint UK_mh5nq8cgkervma0fogy32k6by unique (username)
 alter table PROFILE_EDUCATION add constraint FK5gww9fc4xkxvt866x707lq1yf foreign key (educationList_id) references EDUCATION
 alter table PROFILE_EDUCATION add constraint FK9xtkhgnwcebannrycr6cv24o9 foreign key (Profile_id) references PROFILE
 alter table PROFILE_PROJECT add constraint FK55d8tyu4idmekt5nb4fwk4ket foreign key (projectList_id) references PROJECT
 alter table PROFILE_PROJECT add constraint FKbfb9oko33p9rxqmtws9np6ohv foreign key (Profile_id) references PROFILE
 alter table PROFILE_SKILL add constraint FK8l1b5vamxkekaeinm44gkr5h8 foreign key (skillList_id) references SKILL
 alter table PROFILE_SKILL add constraint FKc41mmkr514oy71au81mk2p627 foreign key (Profile_id) references PROFILE
 alter table PROFILE_WORK_EXPERIENCE add constraint FKsxy2ieifrgogdodukgaq2gx25 foreign key (workExperienceList_id) references EXPERIENCE
 alter table PROFILE_WORK_EXPERIENCE add constraint FK6tdntig7v8w8htm8xbnrtei5d foreign key (Profile_id) references PROFILE
 alter table PROJECT add constraint FKrdni9l81whxjwc0dq1ceve6q3 foreign key (college_id) references EDUCATION
 alter table PROJECT add constraint FKll2lukuxvqrajhf5x706awcuc foreign key (company_id) references EXPERIENCE
 alter table SKILL_EXPERIENCE add constraint FKsom58of6iycrg4vw7g92h3irp foreign key (experiences_id) references EXPERIENCE
 alter table SKILL_EXPERIENCE add constraint FKa82c7c7jyso9w0lubhb0gqhj4 foreign key (skills_id) references SKILL